name: Docker Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t plex-stationarr:latest .

      - name: Update Synology Container
        run: |
          # Stop and remove the old container if it exists
          docker stop plex-stationarr || true
          docker rm plex-stationarr || true
          # Start the new one
          docker run -d --name plex-stationarr -p 8000:3000 plex-stationarr:latest
